name: SWDT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "workspace_publish" ]

  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |         

          $context = Connect-AzAccount -Force

          # Set the context to the appropriate subscription
          Set-AzContext -SubscriptionId ${{ secrets.SUBSCRIPTIONID }} -Context $context
    
          echo "synapseWorkspaceName = wspcunha"
          
          Install-Module -Name "Az.Synapse" -Confirm:$false  -Scope CurrentUser  -Force;
          # Get token for data plane
          $token = Get-AzAccessToken -ResourceUrl https://dev.azuresynapse.net
          
          $authHeader = @{
                  'Content-Type'  = 'application/octet-stream'
                  'Authorization' = 'Bearer ' + $token.Token
          }
              
          $triggersSynapse = Get-AzSynapseTrigger -WorkspaceName "wspcunha";
        
          $triggersSynapse | ForEach-Object { Invoke-WebRequest -Method POST -Uri "https://wspcunha.dev.azuresynapse.net/triggers/$($_.name)/stop?api-version=2020-12-01" -Headers $authHeader}
        
        azPSVersion: latest

      
      #- name: Synapse workspace deployment
      #  uses: Azure/Synapse-workspace-deployment@V1.8.0
      #  with:

         # Provide name of the operation.
      #    operation: 'deploy'
          # Provide the Synapse workspace name where you want to deploy the artifacts.
          # Provide the type of cloud environment. Valid values are: Azure Public, Azure China, Azure US Government, Azure Germany
      #    Environment: 'Azure Public'
      #    TargetWorkspaceName: 'syn-2022-case-repro-flavor2-new'
          # Specify the path to the workspace artifacts template.
      #    TemplateFile: './TemplateForWorkspace.json'
          # Specify the path to the template parameter file.
      #    ParametersFile: './TemplateParametersForWorkspace.json'         
      #    OverrideArmParameters: './params.yaml'
          # Provide the resource group of the target Synapse workspace.
      #    resourceGroup: 'rg-cicd-synapse'
          # Provide client id of service principal.
      #    clientId: ${{ secrets.CLIENTID }}
          # Provide client secret of the service principal.
      #    clientSecret: ${{ secrets.CLIENTSECRET }}
          # Provide subscription id.
      #    subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
          # Provide tenant id.
      #    tenantId: ${{ secrets.TENANTID }}         
          # Deploy managed private endpoints in the template.
      #    deployManagedPrivateEndpoint: false
         
