name: SWDT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "workspace_publish" ]

  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Synapse workspace deployment
        uses: Azure/Synapse-workspace-deployment@V1.8.0
        with:

         # Provide name of the operation.
          operation: 'deploy'
          # Provide the Synapse workspace name where you want to deploy the artifacts.
          # Provide the type of cloud environment. Valid values are: Azure Public, Azure China, Azure US Government, Azure Germany
          Environment: 'Azure Public'
          TargetWorkspaceName: 'syn-2022-case-repro-flavor2-new'
          # Specify the path to the workspace artifacts template.
          TemplateFile: 'TemplateForWorkspace.json'
          # Specify the path to the template parameter file.
          ParametersFile: 'TemplateParametersForWorkspace.json'         
          OverrideArmParameters: '-LS_HANA_BW_referenceName "IR-Synapse-QA" -SapHanaCDSTEST_referenceName "IR-Synapse-QA" -LS_MySql_VRT_referenceName "IR-Synapse-QA" -LS_ORACLE_GAREPPRD_referenceName "IR-Synapse-QA" -LS_MySql_PRTS_referenceName "IR-Synapse-QA" -LS_HANA_BW_referenceName "IR-Synapse-QA" -LS_HANA_SLT_referenceName "IR-Synapse-QA" -LS_HANA_SLT_secret "synapse-sap-hana-slt-prod-cs" -LS_MySql_PRTS_secret "synapse-mysql-prts-prod-cs" -LS_MySql_VRT_secret "synapse-mysql-vrt-prod-cs" -LS_ORACLE_GAREPPRD_secret "synapse-oracle-garepprd-cs" -LS_PostgreSql_PET_referenceName "IR-Synapse-QA" -LS_REST_PowerBI_referenceName "IR-Synapse-QA" -LS_SAP_CDC_referenceName "IR-Synapse-QA" -LS_SqlServer_Bulletin_properties_typeProperties_connectionString_secretName "synapse-sqlserver-bulletin-prod-cs" -LS_SqlServer_Bulletin_pswsecret "synapse-sqlserver-bulletin-prod-cs" -LS_SqlServer_Bulletin_referenceName "IR-Synapse-QA" -LS_SqlServer_COBRA_EMS_properties_typeProperties_connectionString_secretName "synapse-sqlserver-cobra-ems-prod-cs"-LS_SqlServer_COBRA_EMS_pswsecret "synapse-sqlserver-cobra-ems-prod-cs" - LS_SqlServer_COBRA_EMS_referenceName "IR-Synapse-QA" -LS_SqlServer_COBRA_EMS_Staging_properties_typeProperties_connectionString_secretName "synapse-sqlserver-cobra-ems-staging-prod-cs" -LS_SqlServer_COBRA_EMS_Staging_pswsecret "synapse-sqlserver-cobra-ems-staging-prod-cs" -LS_SqlServer_COBRA_EMS_Staging_referenceName "IR-Synapse-QA" -LS_SqlServer_EVMS_properties_typeProperties_connectionString_secretName "synapse-sqlserver-evms-prod-cs" -LS_SqlServer_EVMS_pswsecret "synapse-sqlserver-evms-prod-cs" -LS_SqlServer_EVMS_referenceName "IR-Synapse-QA" -LS_SqlServer_GRIP_properties_typeProperties_connectionString_secretName "synapse-sqlserver-grip-prod-cs" -LS_SqlServer_GRIP_pswsecret "synapse-sqlserver-grip-prod-cs" -LS_SqlServer_GRIP_referenceName "IR-Synapse-QA" -LS_SqlServer_IssueTrak_properties_typeProperties_connectionString_secretName "synapse-sqlserver-issuetrak-prod-cs" -LS_SqlServer_IssueTrak_pswsecret "synapse-sqlserver-issuetrak-prod-cs" -LS_SqlServer_IssueTrak_referenceName "IR-Synapse-QA" -LS_SqlServer_MAP_properties_typeProperties_connectionString_secretName "synapse-sqlserver-map-prod-cs" -LS_SqlServer_MAP_pswsecret "synapse-sqlserver-map-prod-cs" -LS_SqlServer_MAP_referenceName "IR-Synapse-QA" -LS_SqlServer_SiteOps_properties_typeProperties_connectionString_secretName "synapse-sqlserver-siteops-prod-cs" -LS_SqlServer_SiteOps_pswsecret "synapse-sqlserver-siteops-prod-cs" -LS_SqlServer_SiteOps_referenceName "IR-Synapse-QA" -SAP_CDC_Test_referenceName "IR-Synapse-QA" -SapTable_Test_referenceName "IR-Synapse-QA" -IR-Synapse-NonProd_name "IR-Synapse-QA"'
          # Provide the resource group of the target Synapse workspace.
          resourceGroup: 'rg-cicd-synapse'
          # Provide client id of service principal.
          clientId: ${{ secrets.CLIENTID }}
          # Provide client secret of the service principal.
          clientSecret: ${{ secrets.CLIENTSECRET }}
          # Provide subscription id.
          subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
          # Provide tenant id.
          tenantId: ${{ secrets.TENANTID }}         
          # Deploy managed private endpoints in the template.
          deployManagedPrivateEndpoint: false
         
