# This is a basic workflow to help you get started with Actions

name: Synapse Workspace Deployment

# Controls when the workflow will run hj
on:

  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [workspace_publish]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Synapse workspace deployment
        uses: Azure/Synapse-workspace-deployment@V1.7.0
        with:
            # Provide name of the operation.
            operation: 'deploy'
            # Provide the Synapse workspace name where you want to deploy the artifacts.
            TargetWorkspaceName: 'syn-uat-cicd'
            # Specify the path to the workspace artifacts template.
            TemplateFile: 'syn-dev-cicd/TemplateForWorkspace.json'
            # Specify the path to the template parameter file.
            ParametersFile: 'syn-dev-cicd/TemplateParametersForWorkspace.json'                       
            # Provide the type of cloud environment. Valid values are: Azure Public, Azure China, Azure US Government, Azure Germany
            Environment: 'Azure Public'
            # Provide the resource group of the target Synapse workspace.
            resourceGroup: 'rg-syncicd'
            # Provide client id of service principal.
            clientId: ${{ secrets.CLIENTID }}
            # Provide client secret of the service principal.
            clientSecret: ${{ secrets.CLIENTSECRET }}
            # Provide subscription id.
            subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
            # Provide tenant id.
            tenantId: ${{ secrets.TENANTID }}
